name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: build
        run: go build ./...

      - name: vet
        run: go vet ./...
